#Generated by libmep version 2023.3.29.0-beta

import math

def mepx(x, outputs):
  prg = [0] * 50
  prg[0] = x[0]
  prg[1] = prg[0] + prg[0]
  prg[2] = prg[0] + prg[1]
  prg[3] = math.log2(prg[2])
  prg[4] = x[1]
  prg[5] = prg[0] - prg[3]
  prg[6] = x[1]
  prg[7] = math.log2(prg[1])
  prg[8] = x[2]
  prg[9] = x[1]
  prg[10] = x[0]
  prg[11] = prg[0] / prg[5]
  prg[12] = math.exp(prg[3])
  prg[13] = prg[12] / prg[8]
  prg[14] = prg[12] / prg[4]
  prg[15] = math.log2(prg[14])
  prg[16] = x[2]
  prg[17] = prg[3] / prg[9]
  prg[18] = math.pow(10, prg[15])
  prg[19] = prg[14] + prg[7]
  prg[20] = x[2]
  prg[21] = math.log10(prg[8])
  prg[22] = prg[13] + prg[7]
  prg[23] = prg[16] + prg[18]
  prg[24] = x[2]
  prg[25] = x[1]
  prg[26] = x[2]
  prg[27] = prg[26] / prg[5]
  prg[28] = math.log2(prg[2])
  prg[29] = x[0]
  prg[30] = x[0]
  prg[31] = math.pow(prg[20], prg[7])
  prg[32] = prg[22] + prg[21]
  prg[33] = prg[12] * prg[5]
  prg[34] = x[1]
  prg[35] = prg[22] + prg[21]
  prg[36] = x[0]
  prg[37] = x[2]
  prg[38] = x[2]
  prg[39] = x[1]
  prg[40] = prg[7] / prg[29]
  prg[41] = prg[7] - prg[37]
  prg[42] = math.log(prg[13])
  prg[43] = x[1]
  prg[44] = prg[17] - prg[23]
  prg[45] = x[2]
  prg[46] = prg[11] + prg[36]
  prg[47] = x[0]
  prg[48] = prg[28] / prg[8]
  prg[49] = x[1]

  outputs[0] = prg[32]


#example of utilization ...

x = [
2453.000000, 26800.000000, 93.580000]

outputs = [0]

mepx(x, outputs)

print(outputs[0])
